## test_world_prop.gd
## Unit tests for WorldProp (world/props/shared/world_prop.gd) — Slice 5 of
## the world-collision feature.
##
## WorldProp is the base class every discrete prop (boulder, tree, cottage)
## extends. Its entire designer-facing surface is one Vector2i `footprint`;
## everything else — a RectangleShape2D sized and positioned to match it — is
## generated by `_rebuild_collider()`. These tests exercise that generation
## directly. There is no concrete prop scene yet (that's slice 6), so every
## test here works through a minimal fixture instead.
##
## FIXTURE SCENE
## -------------
## world_prop.gd is `@tool` + `StaticBody2D` and expects a CollisionShape2D
## child named "CollisionShape2D" (the @onready `_collision` lookup in the
## class). tests/unit/world/props/shared/fixtures/test_world_prop.tscn stands
## in for a real prop: a bare StaticBody2D with world_prop.gd attached and a
## bare CollisionShape2D child, nothing else. This is the project's first GUT
## fixture scene — mirrored under the test file's own directory rather than
## under source, since it exists only to support these tests.
##
## Written test-first, ahead of world/props/shared/world_prop.gd; the
## implementation has since landed in this same slice.
##
## Design reference: docs/features/world-collision/design.md §8.2, §11
## Test plan: docs/features/world-collision/slice-5-world-prop-test-plan.md
##
## Requires GUT: https://github.com/bitwes/Gut
##
## Run in the Godot editor:
##   Project > Tools > GUT > Run All Tests
## or via CLI:
##   godot --headless -s addons/gut/gut_cmdln.gd \
##     -gselect=test_world_prop.gd -gexit

class_name TestWorldProp
extends GutTest


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

const SCENE_PATH: String = "res://tests/unit/world/props/shared/fixtures/test_world_prop.tscn"

## Physics layer bit for "world" (project.godot [layer_names] 2d_physics/
## layer_1, design doc §11). Duplicated locally rather than referencing
## WorldProp.WORLD_LAYER_BIT so the expected value is legible in this file
## without cross-referencing the production script — same convention as
## tests/integration/player/test_player_scene.gd and
## tests/integration/world/test_solids_collision.gd.
const WORLD_LAYER_BIT: int = 1


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

## Instantiate the fixture scene and add it to the tree so @onready
## `_collision` resolves before the test body runs. The instance is
## autofreed after the test.
## https://github.com/bitwes/Gut/wiki/Double,-Stub,-Spy,-and-More#autofree
##
## @return the instantiated WorldProp root node
func _make_prop() -> WorldProp:
	var packed: PackedScene = load(SCENE_PATH) as PackedScene
	var instance: WorldProp = packed.instantiate() as WorldProp
	add_child_autofree(instance)
	return instance


## Fetch the generated RectangleShape2D off the fixture's CollisionShape2D
## child. Fails the test (and returns null) if either the child or its shape
## is missing or the wrong type, so callers can early-return on null.
func _get_shape(prop: WorldProp) -> RectangleShape2D:
	var collision: CollisionShape2D = prop.get_node("CollisionShape2D") as CollisionShape2D
	assert_not_null(collision,
			"fixture scene must declare a 'CollisionShape2D' child")
	if collision == null:
		return null
	var shape: RectangleShape2D = collision.shape as RectangleShape2D
	assert_not_null(shape,
			"_rebuild_collider() must assign a RectangleShape2D to CollisionShape2D.shape")
	return shape


# ---------------------------------------------------------------------------
# Test 1 — a (1, 1) footprint is one tile's worth of ground
# ---------------------------------------------------------------------------

func test_footprint_1x1_sizes_collider_to_one_tile() -> void:
	var prop: WorldProp = _make_prop()
	prop.footprint = Vector2i(1, 1)

	var shape: RectangleShape2D = _get_shape(prop)
	if shape == null:
		return
	assert_eq(shape.size, Vector2(WorldProp.TILE_SIZE),
			"a (1, 1) footprint should size the collider to exactly one tile (32×16)")


# ---------------------------------------------------------------------------
# Test 2 — a (2, 3) footprint scales both axes by TILE_SIZE
# ---------------------------------------------------------------------------

func test_footprint_2x3_scales_both_axes_by_tile_size() -> void:
	var prop: WorldProp = _make_prop()
	prop.footprint = Vector2i(2, 3)

	var shape: RectangleShape2D = _get_shape(prop)
	if shape == null:
		return
	assert_eq(shape.size, Vector2(64, 48),
			"a (2, 3) footprint should size the collider to Vector2(64, 48) — width and depth both scale with TILE_SIZE")


# ---------------------------------------------------------------------------
# Test 3 — the collider sits entirely behind the ground anchor
# ---------------------------------------------------------------------------

func test_collider_position_y_is_negative_half_depth() -> void:
	# The node origin is the footprint's FRONT edge (design §8.1), so the
	# collider must be offset up-screen by half its depth to span
	# y ∈ [-depth, 0] — never in front of the anchor. Checked for both
	# footprints from the plan to confirm the offset tracks the *generated*
	# size, not a fixed constant.
	var one_by_one: WorldProp = _make_prop()
	one_by_one.footprint = Vector2i(1, 1)
	var shape_a: RectangleShape2D = _get_shape(one_by_one)
	if shape_a != null:
		var collision_a: CollisionShape2D = one_by_one.get_node("CollisionShape2D") as CollisionShape2D
		assert_eq(collision_a.position.y, -shape_a.size.y / 2.0,
				"(1, 1) collider position.y must equal -shape.size.y / 2.0")

	var two_by_three: WorldProp = _make_prop()
	two_by_three.footprint = Vector2i(2, 3)
	var shape_b: RectangleShape2D = _get_shape(two_by_three)
	if shape_b != null:
		var collision_b: CollisionShape2D = two_by_three.get_node("CollisionShape2D") as CollisionShape2D
		assert_eq(collision_b.position.y, -shape_b.size.y / 2.0,
				"(2, 3) collider position.y must equal -shape.size.y / 2.0")


# ---------------------------------------------------------------------------
# Test 4 — the collider stays horizontally centred on the origin
# ---------------------------------------------------------------------------

func test_collider_position_x_is_always_zero() -> void:
	# The origin is the footprint's front-CENTRE (design §8.1) — not its
	# corner — so position.x must stay 0.0 no matter the footprint shape.
	var prop: WorldProp = _make_prop()
	prop.footprint = Vector2i(3, 2)

	var collision: CollisionShape2D = prop.get_node("CollisionShape2D") as CollisionShape2D
	assert_not_null(collision)
	if collision == null:
		return
	assert_eq(collision.position.x, 0.0,
			"collider position.x must remain 0.0 regardless of footprint — the origin is horizontally centred")


# ---------------------------------------------------------------------------
# Test 5 — a designer cannot author a zero or negative footprint
# ---------------------------------------------------------------------------

func test_footprint_clamps_zero_and_negative_axes_to_one() -> void:
	var prop: WorldProp = _make_prop()

	prop.footprint = Vector2i(0, -1)

	assert_eq(prop.footprint, Vector2i(1, 1),
			"Vector2i(0, -1) must clamp to Vector2i(1, 1) — each axis clamps independently to a minimum of 1")


# ---------------------------------------------------------------------------
# Test 6 — reassigning footprint after _ready rebuilds the live collider
# ---------------------------------------------------------------------------

func test_reassigning_footprint_after_ready_rebuilds_collider() -> void:
	# This is what drives the live editor preview described in the class
	# docs (§8.2) — the setter, not just the initial _ready() call, must
	# regenerate the shape.
	var prop: WorldProp = _make_prop()
	var initial_shape: RectangleShape2D = _get_shape(prop)
	if initial_shape == null:
		return
	assert_eq(initial_shape.size, Vector2(WorldProp.TILE_SIZE),
			"sanity check: default footprint (Vector2i.ONE) should start at one tile")

	prop.footprint = Vector2i(2, 2)

	var rebuilt_shape: RectangleShape2D = _get_shape(prop)
	if rebuilt_shape == null:
		return
	assert_eq(rebuilt_shape.size, Vector2(64, 32),
			"reassigning footprint to (2, 2) must rebuild the collider shape to match")


# ---------------------------------------------------------------------------
# Test 7 — setting footprint before the collision child resolves is a no-op,
#          not an error
# ---------------------------------------------------------------------------

func test_footprint_set_before_ready_does_not_error() -> void:
	# WorldProp.new() never enters the scene tree, so @onready _collision is
	# never resolved — it stays null. _rebuild_collider() must guard on that
	# (per the explicit guard comment in the design doc) rather than crashing
	# on a null $CollisionShape2D lookup.
	var prop: WorldProp = WorldProp.new()

	prop.footprint = Vector2i(2, 2)

	# Reaching this line at all is the assertion: a missing/wrong guard would
	# have thrown before we got here. We also confirm the clamped value was
	# still stored, since only the collider rebuild — not the footprint
	# write — is supposed to be skipped pre-_ready.
	assert_eq(prop.footprint, Vector2i(2, 2),
			"footprint should still be stored even though the collider rebuild is a no-op pre-_ready")

	autofree(prop)


# ---------------------------------------------------------------------------
# Test 8 — collision layer/mask match the "world" static-solid convention
# ---------------------------------------------------------------------------

func test_collision_layer_is_world_and_mask_is_empty() -> void:
	# Design doc §11's collision layer table gives WorldProp collision_layer
	# "world" and collision_mask "—" (static; collides with nothing itself —
	# it only needs to BE detected by things that mask in "world", such as
	# the player). collision_mask defaults to 1 in the engine, which happens
	# to equal the "world" bit, so this must be asserted explicitly — a
	# future edit that silently dropped the `collision_mask = 0` line in
	# _ready() would still pass every other test in this file. Same
	# reasoning as the Solids TileSet physics layer assertion in
	# tests/integration/world/test_solids_collision.gd.
	var prop: WorldProp = _make_prop()

	assert_eq(prop.collision_layer, WORLD_LAYER_BIT,
			"WorldProp's collision_layer must be exactly the 'world' layer (bit %d)" % [WORLD_LAYER_BIT])
	assert_eq(prop.collision_mask, 0,
			"WorldProp's collision_mask must be 0 — static solids collide with nothing themselves, "
			+ "they only need to be detected by whatever masks in 'world'")
